# bash RiboViz/scripts/prepRiboviz.sh RibosomeProfilingOtherFungi/NeurosporaYu2015/RiboViz_Yu2015_config.yaml > RibosomeProfilingOtherFungi/NeurosporaYu2015/RiboViz_Yu2015_logfile.txt
dir_in: fastq/Yu2015Neurospora # input directory
dir_out: RibosomeProfilingOtherFungi/NeurosporaYu2015/RiboViz # output directory
dir_tmp: tmp/Yu2015 # tmp directory for intermediate files
rRNA_fasta: RiboVizIndices/Ncrassa_120bputrs/Neurospora_crassa.NC12.rRNA_tRNA.fa # rRNA file to avoid aligning to
orf_fasta: RiboVizIndices/Ncrassa_120bputrs/NC12_CDS_with_120bputrs.fa # orf file to align to
orf_gff_file: RiboVizIndices/Ncrassa_120bputrs/NC12_CDS_120bpL_120bpR.gff3 # GFF2/GFF3 file for ORFs
aligner: hisat2 # short read aligner to use. Currently only hisat2 works
build_indices: FALSE # build indices for aligner? if TRUE, remake indices from fasta files
make_bedgraph: TRUE # output bedgraph.gzs of data, in addition to h5?
dir_index: RiboVizIndices/Ncrassa_120bputrs/NC12/inds # directory to put built indices in
rRNA_index: RiboVizIndices/Ncrassa_120bputrs/NC12/inds/NC12_rRNA_tRNA # rRNA index file
orf_index: RiboVizIndices/Ncrassa_120bputrs/NC12/inds/NC12_CDS_with_120bputrs # ORF index file
fq_files: # fastq files to be processed
  WT: SRR2105977.fastq.gz  # GSM1825738
  # WT-mRNA: SRR2105978.fastq.gz # GSM1825739	
  Opt: SRR2105979.fastq.gz  # GSM1825740
  Cwt-Opt: SRR2105980.fastq.gz  # GSM1825741
adapters: AGATCGGAAGAGCACACGTCT # Illumina sequencing adapter(s) to remove
nprocesses: 8 # number of processes to parallelize over
MinReadLen: 10 # Minimum read length in H5 output
MaxReadLen: 50 # Maximum read length in H5 output
Buffer: 120 # Length of flanking region around the CDS
PrimaryID: Name # Primary gene IDs to access the data (YAL001C, YAL003W, etc.)
SecondID: NULL # Secondary gene IDs to access the data (COX1, EFB1, etc.)
dataset: Yu2015 # Name of the dataset
StopInCDS: TRUE # Are stop codons part of the CDS annotations in GFF?
isTestRun: FALSE # Is this a test run
rpf: TRUE # Is the dataset an RPF or mRNA dataset?
ribovizGFF: TRUE # Does the GFF file contain 3 elements per gene - UTR5, CDS, and UTR3
features_file: NULL
do_pos_sp_nt_freq: FALSE
