adapters: AGATCGGAAGAGCACACGTCT
aligner: hisat2
asite_disp_length_file: data/yeast_standard_asite_disp_length.txt
buffer: 120
build_indices: true
cmd_file: run_riboviz_Yu_2015_Nc.sh
codon_positions_file: null
count_reads: true
count_threshold: 64
dataset: Yu2015
dedup_stats: false
dedup_umis: false
dir_index: Yu_2015_Nc/index # Built indices directory
dir_in: Yu_2015_Nc/input # Input directory
dir_logs: Yu_2015_Nc/logs # Log files directory
dir_out: Yu_2015_Nc/output # Output directory
dir_tmp: Yu_2015_Nc/tmp # Intermediate files directory
do_pos_sp_nt_freq: false
extract_umis: false
features_file: null
fq_files:
  Cwt-Opt: SRR2105980.fastq.gz
  Opt: SRR2105979.fastq.gz
  WT: SRR2105977.fastq.gz
group_umis: false
is_riboviz_gff: true
is_test_run: false
make_bedgraph: true
max_read_length: 50
min_read_length: 10
multiplex_fq_files: null
num_processes: 8
orf_fasta_file: ../../riboviz/example-datasets/fungi/neurospora/annotation/NC12_CDS_with_120bputrs.fa
orf_gff_file:  ../../riboviz/example-datasets/fungi/neurospora/annotation/NC12_CDS_120bpL_120bpR.gff3
orf_index_prefix: NC12_CDS_with_120bputrs
primary_id: Name
publish_index_tmp: false
rpf: true
rrna_fasta_file: ../../riboviz/example-datasets/fungi/neurospora/contaminants/Neurospora_crassa_NC12_rRNA_tRNA.fa
rrna_index_prefix: NC12_rRNA_tRNA
sample_sheet: null
secondary_id: null
stop_in_cds: true
t_rna_file: null
umi_regexp: null
